tasks:
  - init: pip install livereload brython && livereload
    command: gp open script.py && gp preview $(gp url 35729)/index.html

ports:
  - port: 35729
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
