tasks:
  - init: pip install livereload brython
    command: gp open script.py && livereload

ports:
  - port: 35729
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
