tasks:
  - init: pip install livereload brython
    command: gp open script.py && livereload & gp await-port 35729 && gp preview $(gp url 35729)/index.html && exit

ports:
  - port: 35729
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
