tasks:
  - init: pip install livereload brython
    command: livereload && gp open script.py

ports:
  - port: 35729
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
