tasks:
  - init: pip install livereload brython
    command: livereload & gp open script.py && gp await-port 35729 && sleep 5 && gp preview $(gp url 35729)/index.html && exit

ports:
  - port: 35729
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
